[package]
name = "elrond-exec-service-wasmer"
version = "0.0.1"
edition = "2021"

[lib]

[dependencies]
elrond-exec-service = { path = "../exec-service" }

# We rename `wasmer` to `wasmer-api` to avoid the conflict with this
# library name (see `[lib]`).
# wasmer = { version = "=2.2.1", default-features = true, features = [
#     "sys",
#     "wasmparser",
# ], package = "wasmer" }
# wasmer-compiler-singlepass = { version = "=2.2.1" }
# wasmer-engine = { version = "=2.2.1"}
# wasmer-engine-universal = { version = "=2.2.1" }
# wasmer-middlewares = { version = "=2.2.1" }
# wasmer-types = { version = "=2.2.1" }
# enumset = "1.0"
# cfg-if = "1.0"
# lazy_static = "1.4"
# libc = { version = "^0.2", default-features = false }
# serde = { version = "1", optional = true, features = ["derive"] }
# thiserror = "1"
# typetag = { version = "0.1", optional = true }
# paste = "1.0"
# anyhow = "1.0"

# env_logger = "0.8.4"
# log = "0.4.14"
