name: Builds and tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  rust_test:
    name: Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions-rs/toolchain@v1.0.6
        with:
          default: true
          toolchain: stable
      - name: Run rust tests
        run: cargo test
  clippy_check:
    permissions: write-all
    name: Clippy linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.5.0
      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          components: clippy
          default: true
      - uses: actions-rs/clippy-check@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
